version: "3.9"
services:
  ansible:
    build:
      context: Dockerfiles/
      dockerfile: Ansible.Dockerfile
    command: sh
    tty: true
    volumes:
      - ./playbooks:/ansible/playbooks
      - ./inventory:/ansible/inventory
      - ssh-volume:/home/root/.ssh/ansible/public_keys
    networks:
      netsible:
        ipv4_address: ${ANSIBLE_IP}

  rockylinux:
    build:
      context: Dockerfiles/
      dockerfile: Rockylinux.Dockerfile
    ports:
      - "2222"
    volumes:
      - ssh-volume:/home/Ansible/.ssh/authorized_keys
    depends_on:
      - "ansible"
    networks:
      netsible:
        ipv4_address: ${ROCKY_IP}

  ubuntu20:
    build:
      context: Dockerfiles/
      dockerfile: Ubuntu20.Dockerfile
    ports:
      - "2222"
    volumes:
      - ssh-volume:/home/Ansible/.ssh/authorized_keys
    depends_on:
      - "ansible"
    networks:
      netsible:
        ipv4_address: ${UBUNTU20_IP}
  
  ubuntu21:
    build:
      context: Dockerfiles/
      dockerfile: Ubuntu21.Dockerfile
    ports:
      - "2222"
    volumes:
      - ssh-volume:/home/Ansible/.ssh/authorized_keys
    depends_on:
      - "ansible"
    networks:
      netsible:
        ipv4_address: ${UBUNTU21_IP}

  ubuntu22:
    build:
      context: Dockerfiles/
      dockerfile: Ubuntu22.Dockerfile
    ports:
      - "2222"
    volumes:
      - ssh-volume:/home/Ansible/.ssh/authorized_keys
    depends_on:
      - "ansible"
    networks:
      netsible:
        ipv4_address: ${UBUNTU22_IP}

  debian:
    build:
      context: Dockerfiles/
      dockerfile: Debian.Dockerfile
    ports:
      - "2222"
    volumes:
      - ssh-volume:/home/Ansible/.ssh/authorized_keys
    depends_on:
      - "ansible"
    networks:
      netsible:
        ipv4_address: ${DEBIAN_IP}
    
volumes:
  ssh-volume:
networks:
  netsible:
    driver: bridge
    ipam:
     config:
       - subnet: ${SUBNET_RANGE}
         gateway: ${GATEWAY_IP}