version: "3.9"
services:
  ansible:
    image: willhallonline/ansible:2.12-alpine-3.15 # <-- you can update this via https://hub.docker.com/r/willhallonline/ansible
    networks:
      netsible:
        ipv4_address: 172.16.0.2
  rockylinux:
    build:
      context: Dockerfiles/
      dockerfile: Rockylinux.Dockerfile
    ports:
      - "2222:22"
    volumes:
      - ./ssh/ansible.pub:/home/Ansible/.ssh/authorized_keys
    networks:
      netsible:
        ipv4_address: 172.16.0.10

networks:
  netsible:
    driver: bridge
    ipam:
     config:
       - subnet: 172.16.0.0/16
         gateway: 172.16.0.1